export const employees = [
  { value: "Ivanov", name: "Alexander Ivanov" },
  { value: "Petrov", name: "Dmitry Petrov" },
  { value: "Sidorov", name: "Sergey Sidorov" },
  { value: "Smirnov", name: "Alexey Smirnov" },
  { value: "Kuznetsov", name: "Andrey Kuznetsov" },
  { value: "Popov", name: "Vladimir Popov" },
  { value: "Lebedev", name: "Ivan Lebedev" },
  { value: "Kozlov", name: "Nikolay Kozlov" },
  { value: "Novikov", name: "Pavel Novikov" },
  { value: "Morozov", name: "Mikhail Morozov" },
  { value: "Volkov", name: "Egor Volkov" },
  { value: "Solovyov", name: "Artem Solovyov" },
  { value: "Vasilyev", name: "Denis Vasilyev" },
  { value: "Zaitsev", name: "Roman Zaitsev" },
  { value: "Pavlov", name: "Konstantin Pavlov" },
  { value: "Semyonov", name: "Viktor Semyonov" },
  { value: "Golubev", name: "Oleg Golubev" },
  { value: "Vinogradov", name: "Yuri Vinogradov" },
  { value: "Bogdanov", name: "Stanislav Bogdanov" },
  { value: "Voronin", name: "Anatoly Voronin" },
];
